swagger: "2.0"
info:
  title: Task API
  description: API for managing tasks
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        200:
          description: List of tasks
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
    post:
      summary: Create a new task
      consumes:
        - application/json
      parameters:
        - in: body
          name: task
          description: Task to create
          schema:
            $ref: '#/definitions/Task'
      responses:
        201:
          description: Task created
          schema:
            $ref: '#/definitions/Task'

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Task found
          schema:
            $ref: '#/definitions/Task'
        404:
          description: Task not found
    put:
      summary: Update a task
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: task
          description: Task to update
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: Task updated
          schema:
            $ref: '#/definitions/Task'
    delete:
      summary: Delete a task
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        204:
          description: Task deleted

definitions:
  Task:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      status:
        type: string
    required:
      - id
      - title
      - status